from typing import Dict, Any, List, Optional
from brain.services.brain_service import BrainService

class ContextBuilder:
    """
    Builds structured, targeted prompt contexts for specialist agents,
    retrieving only decisions, artifacts, and feedback relevant to the agent's inputs.
    """
    def __init__(self):
        self.brain_service = BrainService()

    def build_context_for_agent(self, session_id: str, agent_name: str) -> str:
        # 1. Fetch agent configuration to determine target inputs
        agent = self.brain_service.get_registered_agent(agent_name)
        inputs = agent.get("inputs", []) if agent else []
        
        # 2. Fetch session details to check current state & human feedback
        session = self.brain_service.get_session(session_id)
        active_node = session.get("active_node") if session else "unknown"
        feedback = []
        if session and "dag" in session and "history" in session["dag"]:
            # Gather relevant history records
            feedback = [
                h for h in session["dag"]["history"] 
                if h.get("node_id") == active_node or h.get("action") == "HUMAN_REJECTION"
            ]

        # 3. Retrieve decisions and filter by input boundaries
        decisions = self.brain_service.list_session_decisions(session_id)
        # 4. Retrieve artifacts
        artifacts = self.brain_service.list_session_artifacts(session_id)

        # 5. Build the context output string
        lines = []
        lines.append(f"# Active Session Context: {session_id}")
        lines.append(f"Target Agent: {agent_name}")
        lines.append(f"Current Workflow Node: {active_node}\n")

        # Dynamic mapping of agent input scopes
        lines.append("## Relevant Shared Memory State")
        
        # Decisions Section
        lines.append("### Decisions & Rationale")
        matching_decisions = []
        for d in decisions:
            # Check if this decision is relevant based on the agent's inputs
            # e.g., if the agent requires "prd_spec" and the decision was made in "planning_node"
            is_relevant = False
            if not inputs:
                is_relevant = True
            else:
                for inp in inputs:
                    inp_lower = inp.lower()
                    if (inp_lower in d.get("node", "").lower() or 
                        inp_lower in d.get("title", "").lower() or
                        any(inp_lower in art.lower() for art in d.get("artifacts_produced", []))):
                        is_relevant = True
                        break
            if is_relevant:
                matching_decisions.append(d)

        if not matching_decisions:
            lines.append("- No relevant design decisions recorded yet.")
        else:
            for d in matching_decisions:
                lines.append(f"#### Decision: {d.get('title')}")
                lines.append(f"- **Agent**: {d.get('agent')}")
                lines.append(f"- **Node**: {d.get('node')}")
                lines.append(f"- **Rationale**: {d.get('rationale')}")
                lines.append(f"- **Confidence Score**: {int(d.get('confidence_score', 0) * 100)}%")
                if d.get("alternatives_considered"):
                    lines.append(f"- **Alternatives**: {', '.join(d.get('alternatives_considered'))}")
                lines.append("")

        # Artifacts Section
        lines.append("### Active Blueprint Artifacts")
        matching_artifacts = []
        for a in artifacts:
            is_relevant = False
            if not inputs:
                is_relevant = True
            else:
                for inp in inputs:
                    if inp.lower() in a.get("type", "").lower() or inp.lower() in a.get("file_path", "").lower():
                        is_relevant = True
                        break
            if is_relevant:
                matching_artifacts.append(a)

        if not matching_artifacts:
            lines.append("- No relevant artifacts generated in workspace yet.")
        else:
            for a in matching_artifacts:
                lines.append(f"- **File**: {a.get('file_path')} (v{a.get('version', 1)})")
                lines.append(f"  - **Type**: {a.get('type')}")
                lines.append(f"  - **Generated By**: {a.get('generated_by')}")
                if a.get("depends_on"):
                    lines.append(f"  - **Depends On**: {', '.join(a.get('depends_on'))}")
                if a.get("used_by"):
                    lines.append(f"  - **Used By**: {', '.join(a.get('used_by'))}")
                lines.append("")

        # Human & System Feedback Loops Section
        if feedback:
            lines.append("### Active Revision Requests & Human Feedback")
            for f in feedback:
                lines.append(f"- **Action**: {f.get('action')} at {f.get('timestamp')}")
                lines.append(f"  - **Details**: {f.get('details')}")
                lines.append("")

        return "\n".join(lines)
