import json
import logging
from typing import List, Optional, Dict, Any
from mcp.server.fastmcp import FastMCP

from brain.services.brain_service import BrainService
from brain.services.context_builder import ContextBuilder

# Initialize FastMCP Server
mcp = FastMCP("Project Brain Memory Server")

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_brain_server")

# Instantiate Core Business Services
def get_service() -> BrainService:
    return BrainService()

def get_context_builder() -> ContextBuilder:
    return ContextBuilder()

@mcp.tool()
def register_agent(
    name: str,
    description: str,
    system_prompt: str,
    inputs: List[str] = [],
    outputs: List[str] = [],
    skills: List[str] = [],
    mcp_servers: List[str] = []
) -> str:
    """
    Registers a dynamic agent and its capabilities in the Agent Registry.
    """
    try:
        service = get_service()
        agent_data = {
            "name": name,
            "description": description,
            "status": "active",
            "system_prompt": system_prompt,
            "inputs": inputs,
            "outputs": outputs,
            "skills": skills,
            "mcp_servers": mcp_servers
        }
        res = service.register_agent(agent_data)
        return json.dumps({"status": "success", "agent": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in register_agent: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def create_project(name: str, description: Optional[str] = None) -> str:
    """
    Creates a new project profile mapping session directories.
    """
    try:
        service = get_service()
        res = service.create_project(name, description)
        return json.dumps({"status": "success", "project": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in create_project: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def create_session(project_id: str, git_commit_hash: Optional[str] = None, dag: Optional[Dict[str, Any]] = None) -> str:
    """
    Initializes a session runner context tracking task execution DAG structures.
    """
    try:
        service = get_service()
        res = service.create_session(project_id, git_commit_hash, dag)
        return json.dumps({"status": "success", "session": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in create_session: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def update_session_state(
    session_id: str,
    active_node: Optional[str] = None,
    status: Optional[str] = None,
    git_commit_hash: Optional[str] = None,
    dag: Optional[Dict[str, Any]] = None
) -> str:
    """
    Updates the session active node, status, commit, or execution DAG.
    """
    try:
        service = get_service()
        updates = {}
        if active_node is not None:
            updates["active_node"] = active_node
        if status is not None:
            updates["status"] = status
        if git_commit_hash is not None:
            updates["git_commit_hash"] = git_commit_hash
        if dag is not None:
            updates["dag"] = dag

        res = service.update_session(session_id, updates)
        if not res:
            return json.dumps({"status": "error", "message": "Session not found"})
        return json.dumps({"status": "success", "session": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in update_session_state: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def store_artifact(
    session_id: str,
    file_path: str,
    checksum: str,
    type: str,
    generated_by: str,
    depends_on: List[str] = [],
    used_by: List[str] = []
) -> str:
    """
    Registers or updates an artifact generated by a workflow process. Auto-increments versions.
    """
    try:
        service = get_service()
        artifact_data = {
            "session_id": session_id,
            "file_path": file_path,
            "checksum": checksum,
            "type": type,
            "generated_by": generated_by,
            "depends_on": depends_on,
            "used_by": used_by
        }
        res = service.store_artifact(artifact_data)
        return json.dumps({"status": "success", "artifact": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in store_artifact: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def store_decision(
    session_id: str,
    node: str,
    agent: str,
    title: str,
    rationale: str,
    confidence_score: float,
    alternatives_considered: List[str] = [],
    dependencies: List[str] = [],
    artifacts_produced: List[str] = []
) -> str:
    """
    Commits a design decision made by a specialist agent to Project Brain.
    """
    try:
        service = get_service()
        decision_data = {
            "session_id": session_id,
            "node": node,
            "agent": agent,
            "title": title,
            "rationale": rationale,
            "confidence_score": confidence_score,
            "alternatives_considered": alternatives_considered,
            "dependencies": dependencies,
            "artifacts_produced": artifacts_produced
        }
        res = service.store_decision(decision_data)
        return json.dumps({"status": "success", "decision": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in store_decision: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def store_evaluation(
    session_id: str,
    completeness_score: float,
    completeness_details: Optional[str],
    consistency_score: float,
    consistency_details: Optional[str],
    security_score: float,
    security_details: Optional[str],
    documentation_quality_score: float,
    documentation_quality_details: Optional[str],
    deployability_score: float,
    deployability_details: Optional[str],
    composite_score: float,
    passed: bool,
    logs: List[str] = [],
    findings: List[Dict[str, Any]] = []
) -> str:
    """
    Logs the Quality Gate evaluation scores and findings for a session.
    """
    try:
        service = get_service()
        evaluation_data = {
            "session_id": session_id,
            "completeness": {"score": completeness_score, "details": completeness_details},
            "consistency": {"score": consistency_score, "details": consistency_details},
            "security": {"score": security_score, "details": security_details},
            "documentation_quality": {"score": documentation_quality_score, "details": documentation_quality_details},
            "deployability": {"score": deployability_score, "details": deployability_details},
            "composite_score": composite_score,
            "passed": passed,
            "logs": logs,
            "findings": findings
        }
        res = service.store_evaluation(evaluation_data)
        return json.dumps({"status": "success", "evaluation": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in store_evaluation: {e}")
        return json.dumps({"status": "error", "message": str(e)})

@mcp.tool()
def get_agent_context(session_id: str, agent_name: str) -> str:
    """
    Builds the dynamic targeted memory context for a specialist agent.
    """
    try:
        builder = get_context_builder()
        context = builder.build_context_for_agent(session_id, agent_name)
        return context
    except Exception as e:
        logger.error(f"Error in get_agent_context: {e}")
        return f"Error retrieving context for agent: {e}"

@mcp.tool()
def log_audit_action(session_id: str, agent: str, action: str, details: Dict[str, Any] = {}) -> str:
    """
    Appends a new system activity audit log record.
    """
    try:
        service = get_service()
        res = service.log_audit(session_id, agent, action, details)
        return json.dumps({"status": "success", "audit": res}, indent=2)
    except Exception as e:
        logger.error(f"Error in log_audit_action: {e}")
        return json.dumps({"status": "error", "message": str(e)})

if __name__ == "__main__":
    mcp.run()
