from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime, timezone
from typing import List, Optional

class DecisionBase(BaseModel):
    session_id: str = Field(..., description="Active session ID")
    node: str = Field(..., description="Active workflow node ID where decision was made")
    agent: str = Field(..., description="Name of the agent making the decision")
    title: str = Field(..., description="A short summary description of the decision")
    rationale: str = Field(..., description="Detail explanation of the reasoning and design trade-offs")
    alternatives_considered: List[str] = Field(default_factory=list, description="Other choices evaluated")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence rating between 0.0 and 1.0")
    dependencies: List[str] = Field(default_factory=list, description="IDs of earlier decisions this decision depends on")
    artifacts_produced: List[str] = Field(default_factory=list, description="File paths or artifact IDs generated by this decision")

class DecisionCreate(DecisionBase):
    pass

class Decision(DecisionBase):
    model_config = ConfigDict(from_attributes=True)

    id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
